version: '3.8'

networks:
  goShort:

services:
  short:
    build:
      context: ./
      dockerfile: ./Dockerfile 
    restart: always
    networks:
      - goShort
    ports: 
    - 80:80
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      PGDATA: /data/postgres
    networks:
      - goShort
    volumes:
       - database-data:/data/postgres
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  database-data: