name: CI

on:
  push:
    branches:
      - '*'

jobs: 
  tests: 
    name: Run Tests
    matrix:
        go-version: [1.18.x, 1.19.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps: 
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Verify Dependencies
        run: go mod verify
      - name: build
        run: go build -v ./...
      - name: run vet
        run: go vet ./...
      - name: Test
        run: go test -vet=off ./...